[configuration]
port = "50056" # It is important to use the port from here
run = "python src/eval_ad45335_dac/server.py" # This is the run command, can use any language this way
proto = "./proto" # This is the directory where the proto files are contained
requests_to_influx = true # This is to send any incoming requests to influx, this goes through the manager 